### ISSUE TITLE
css in dom

### ISSUE THREAD

**Issue by Hadeel-Salamin** [fack2/music_5#34]
you would write a class in CSS and these properties in a css file, and assign this class to an element in dom file instead of having all these CSS lines in dom file

**Comment by jema28** [comment]
Yes, see lines below: 
https://github.com/fack2/music_5/blob/0656e90939ba76bc5e5a28d841cfb63828805fda/public/dom.js#L34-L37

**Comment by Nadeen123** [comment]
#45 done
